worker_processes auto;

events {
  worker_connections  1024;
  multi_accept on;
  use epoll;
}

http {
  proxy_cache_path /dev/shm
  levels=1:2
  keys_zone=cache-space:4m
  max_size=50m
  inactive=120m;
  limit_conn_zone $binary_remote_addr zone=lcz:10m;
  limit_req_zone $binary_remote_addr zone=lrz:10m rate=20r/s;

  log_format ltsv 'domain:$host\t'
                  'host:$remote_addr\t'
                  'user:$remote_user\t'
                  'time:$time_local\t'
                  'method:$request_method\t'
                  'path:$request_uri\t'
                  'protocol:$server_protocol\t'
                  'status:$status\t'
                  'size:$body_bytes_sent\t'
                  'referer:$http_referer\t'
                  'agent:$http_user_agent\t'
                  'response_time:$request_time\t'
                  'cookie:$http_cookie\t'
                  'set_cookie:$sent_http_set_cookie\t'
                  'upstream_addr:$upstream_addr\t'
                  'upstream_cache_status:$upstream_cache_status\t'
                  'upstream_response_time:$upstream_response_time';

  include /etc/nginx/conf.d/*.conf;
}
